In [212]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [204]:
data = pd.read_csv(r"D:\data_science_4achievers\dataset_project2\Resume.csv")

In [205]:
data["Resume_str"].head()
data.head()

         ID  \
0  16852973
1  22323967
2  33176873
3  27018550
4  17812897

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Resume_str  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           HR ADMINISTRATOR/MARKETING ASSOCIATE\n\nHR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate\n\nHR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate     Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         Assistant General Manager     Jun 2010   to   Dec 2010      Company Name   －   City  ,   State     Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  Handled daily operations and reported directly to the corporate office.  Hired and trained staff on overall objectives and goals with an emphasis on high customer service.  Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.         Executive Support / Marketing Assistant     Jul 2007   to   Jun 2010      Company Name   －   City  ,   State     Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.  Managed front-end operations to ensure friendly and efficient transactions.  Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         Reservation & Front Office Manager     Jun 2004   to   Jul 2007      Company Name   －   City  ,   State          Owner/ Partner     Dec 2001   to   May 2004      Company Name   －   City  ,   State          Price Integrity Coordinator     Aug 1999   to   Dec 2001      Company Name   －   City  ,   State          Education      N/A  ,   Business Administration   1999     Jefferson College   －   City  ,   State       Business Administration  Marketing / Advertising         High School Diploma  ,   College Prep. studies   1998     Sainte Genevieve Senior High   －   City  ,   State       Awarded American Shrubel Leadership Scholarship to Jefferson College         Skills     Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.

In [110]:
import re                                    # for pattern based text cleaning
import nltk                                  # natural language toolkit library
from nltk.corpus import stopwords            # common words like "the", "is", "and"
from nltk.stem import WordNetLemmatizer      # converts words to their base form
from sklearn.preprocessing import LabelEncoder  # converts text labels to numbers

nltk.download('stopwords')   # downloads the stopwords list
nltk.download('wordnet')     # downloads the dictionary used by lemmatizer

[nltk_data] Downloading package stopwords to C:\Users\YASHUB
[nltk_data]     HAYAT\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\YASHUB
[nltk_data]     HAYAT\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [112]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [114]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

In [144]:
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV

In [148]:
from sklearn.naive_bayes import MultinomialNB

In [154]:
from sklearn.ensemble import RandomForestClassifier

In [168]:
!pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in c:\users\yashub hayat\anaconda3\lib\site-packages (from lightgbm) (1.26.4)
Requirement already satisfied: scipy in c:\users\yashub hayat\anaconda3\lib\site-packages (from lightgbm) (1.16.0)
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.5 MB 10.9 MB/s eta 0:00:01
   -------------------------- ------------- 1.0/1.5 MB 12.2 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.5 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 10.2 MB/s eta 0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

In [160]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\yashub hayat\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\yashub hayat\anaconda3\lib\site-packages (from xgboost) (1.16.0)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB 9.9 MB/s eta 0:00:11
   ---------------------------------------- 0.9/101.7 MB 11.9 MB/s eta 0:00:09
    --------------------------------------- 1.6/101.7 MB 12.5 MB/s eta 0:00:09
    --------------------------------------- 2.2/101.7 MB 12.7 MB/s eta 0:00:08
   - -------------------------------------- 2.8/101.7 MB 12.9 MB/s eta 0:00:08
   - -------------------------------------- 3.5/101.7 MB 13.0 MB/s eta 0:00:08
   - -------------------------------------- 4.1/101.7 MB 13.1 MB/s eta 0:00:08
   - -------------------------------------- 4.7/101.7 MB 13.0 MB/s eta 0:00:08
   -- ------------------------------------- 5.3/101.7 MB 13.0 MB/s eta 0:00:08
   -- ------------------------------------- 5.9/101.7 MB 13.1 MB/s eta 0:00:08
   -- ------------------------------------- 6.6/101.7 MB 13.1 MB/s eta 0:00:08
   -- ------------------------------------- 7.2/101.7 MB 13.2 MB/s eta 0:00:08
   --- ------------------------------------ 7.8/101.7 MB 13.2 MB/s eta 0:00:08
   --- ------------------------------------ 8.4/101.7 MB 13.2 MB/s eta 0:00:08
   --- ------------------------------------ 9.0/101.7 MB 13.1 MB/s eta 0:00:08
   --- ------------------------------------ 9.7/101.7 MB 13.1 MB/s eta 0:00:08
   ---- ----------------------------------- 10.3/101.7 MB 13.1 MB/s eta 0:00:07
   ---- ----------------------------------- 10.9/101.7 MB 13.4 MB/s eta 0:00:07
   ---- ----------------------------------- 11.6/101.7 MB 13.4 MB/s eta 0:00:07
   ---- ----------------------------------- 12.2/101.7 MB 13.4 MB/s eta 0:00:07
   ----- ---------------------------------- 12.8/101.7 MB 13.4 MB/s eta 0:00:07
   ----- ---------------------------------- 13.4/101.7 MB 13.4 MB/s eta 0:00:07
   ----- ---------------------------------- 14.1/101.7 MB 13.4 MB/s eta 0:00:07
   ----- ---------------------------------- 14.7/101.7 MB 13.4 MB/s eta 0:00:07
   ------ --------------------------------- 15.4/101.7 MB 13.4 MB/s eta 0:00:07
   ------ --------------------------------- 16.0/101.7 MB 13.4 MB/s eta 0:00:07
   ------ --------------------------------- 16.6/101.7 MB 13.4 MB/s eta 0:00:07
   ------ --------------------------------- 17.2/101.7 MB 13.4 MB/s eta 0:00:07
   ------- -------------------------------- 17.8/101.7 MB 13.4 MB/s eta 0:00:07
   ------- -------------------------------- 18.5/101.7 MB 13.4 MB/s eta 0:00:07
   ------- -------------------------------- 19.1/101.7 MB 13.4 MB/s eta 0:00:07
   ------- -------------------------------- 19.9/101.7 MB 13.6 MB/s eta 0:00:06
   -------- ------------------------------- 20.6/101.7 MB 13.6 MB/s eta 0:00:06
   -------- ------------------------------- 21.2/101.7 MB 13.4 MB/s eta 0:00:07
   -------- ------------------------------- 21.8/101.7 MB 13.4 MB/s eta 0:00:06
   -------- ------------------------------- 22.5/101.7 MB 13.4 MB/s eta 0:00:06
   --------- ------------------------------ 23.1/101.7 MB 13.6 MB/s eta 0:00:06
   --------- ------------------------------ 23.7/101.7 MB 13.6 MB/s eta 0:00:06
   --------- ------------------------------ 24.4/101.7 MB 13.6 MB/s eta 0:00:06
   --------- ------------------------------ 25.0/101.7 MB 13.6 MB/s eta 0:00:06
   ---------- ----------------------------- 25.6/101.7 MB 13.6 MB/s eta 0:00:06
   ---------- ----------------------------- 26.2/101.7 MB 13.6 MB/s eta 0:00:06
   ---------- ----------------------------- 26.9/101.7 MB 13.6 MB/s eta 0:00:06
   ---------- ----------------------------- 27.5/101.7 MB 13.6 MB/s eta 0:00:06
   ----------- ---------------------------- 28.1/101.7 MB 13.6 MB/s eta 0:00:06
   ----------- ---------------------------- 28.8/101.7 MB 13.6 MB/s eta 0:00:06
   ----------- ---------------------------- 29.4/101.7 MB 13.6 MB/s eta 0:00:06
   ----------- ---------------------------- 30.0/101.7 MB 13.6 MB/s eta 0:00:06
   ------------ --------------------------- 30.7/101.7 MB 13.6 MB/s eta 0:00:06
   ------------ --------------------------- 31.3/101.7 MB 13.6 MB/s eta 0:00:06
   ------------ --------------------------- 31.9/101.7 MB 13.6 MB/s eta 0:00:06
   ------------ --------------------------- 32.6/101.7 MB 13.6 MB/s eta 0:00:06
   ------------ --------------------------- 32.9/101.7 MB 13.4 MB/s eta 0:00:06
   ------------- -------------------------- 33.6/101.7 MB 13.4 MB/s eta 0:00:06
   ------------- -------------------------- 34.0/101.7 MB 13.1 MB/s eta 0:00:06
   ------------- -------------------------- 34.7/101.7 MB 13.1 MB/s eta 0:00:06
   ------------- -------------------------- 35.1/101.7 MB 12.8 MB/s eta 0:00:06
   -------------- ------------------------- 35.8/101.7 MB 12.8 MB/s eta 0:00:06
   -------------- ------------------------- 36.3/101.7 MB 12.8 MB/s eta 0:00:06
   -------------- ------------------------- 36.9/101.7 MB 12.8 MB/s eta 0:00:06
   -------------- ------------------------- 37.6/101.7 MB 12.8 MB/s eta 0:00:05
   --------------- ------------------------ 38.2/101.7 MB 12.9 MB/s eta 0:00:05
   --------------- ------------------------ 38.8/101.7 MB 12.8 MB/s eta 0:00:05
   --------------- ------------------------ 39.4/101.7 MB 12.6 MB/s eta 0:00:05
   --------------- ------------------------ 40.0/101.7 MB 12.6 MB/s eta 0:00:05
   ---------------- ----------------------- 40.7/101.7 MB 12.6 MB/s eta 0:00:05
   ---------------- ----------------------- 41.3/101.7 MB 12.6 MB/s eta 0:00:05
   ---------------- ----------------------- 42.0/101.7 MB 12.6 MB/s eta 0:00:05
   ---------------- ----------------------- 42.6/101.7 MB 12.8 MB/s eta 0:00:05
   ---------------- ----------------------- 43.2/101.7 MB 13.1 MB/s eta 0:00:05
   ----------------- ---------------------- 43.8/101.7 MB 13.1 MB/s eta 0:00:05
   ----------------- ---------------------- 44.5/101.7 MB 13.1 MB/s eta 0:00:05
   ----------------- ---------------------- 45.1/101.7 MB 13.1 MB/s eta 0:00:05
   ----------------- ---------------------- 45.7/101.7 MB 13.4 MB/s eta 0:00:05
   ------------------ --------------------- 46.4/101.7 MB 13.6 MB/s eta 0:00:05
   ------------------ --------------------- 47.0/101.7 MB 13.4 MB/s eta 0:00:05
   ------------------ --------------------- 47.6/101.7 MB 13.4 MB/s eta 0:00:05
   ------------------ --------------------- 48.2/101.7 MB 13.4 MB/s eta 0:00:04
   ------------------- -------------------- 48.9/101.7 MB 13.6 MB/s eta 0:00:04
   ------------------- -------------------- 49.5/101.7 MB 13.4 MB/s eta 0:00:04
   ------------------- -------------------- 50.2/101.7 MB 13.4 MB/s eta 0:00:04
   ------------------- -------------------- 50.8/101.7 MB 13.4 MB/s eta 0:00:04
   -------------------- ------------------- 51.4/101.7 MB 13.4 MB/s eta 0:00:04
   -------------------- ------------------- 52.0/101.7 MB 13.4 MB/s eta 0:00:04
   -------------------- ------------------- 52.7/101.7 MB 13.4 MB/s eta 0:00:04
   -------------------- ------------------- 53.3/101.7 MB 13.4 MB/s eta 0:00:04
   --------------------- ------------------ 53.9/101.7 MB 13.4 MB/s eta 0:00:04
   --------------------- ------------------ 54.6/101.7 MB 13.4 MB/s eta 0:00:04
   --------------------- ------------------ 55.2/101.7 MB 13.4 MB/s eta 0:00:04
   --------------------- ------------------ 55.8/101.7 MB 13.4 MB/s eta 0:00:04
   ---------------------- ----------------- 56.5/101.7 MB 13.4 MB/s eta 0:00:04
   ---------------------- ----------------- 57.1/101.7 MB 13.4 MB/s eta 0:00:04
   ---------------------- ----------------- 57.7/101.7 MB 13.4 MB/s eta 0:00:04
   ---------------------- ----------------- 58.4/101.7 MB 13.4 MB/s eta 0:00:04
   ----------------------- ---------------- 59.0/101.7 MB 13.4 MB/s eta 0:00:04
   ----------------------- ---------------- 59.6/101.7 MB 13.4 MB/s eta 0:00:04
   ----------------------- ---------------- 60.2/101.7 MB 13.4 MB/s eta 0:00:04
   ----------------------- ---------------- 60.8/101.7 MB 13.4 MB/s eta 0:00:04
   ------------------------ --------------- 61.5/101.7 MB 13.4 MB/s eta 0:00:04
   ------------------------ --------------- 62.1/101.7 MB 13.4 MB/s eta 0:00:03
   ------------------------ --------------- 62.7/101.7 MB 13.4 MB/s eta 0:00:03
   ------------------------ --------------- 63.4/101.7 MB 13.4 MB/s eta 0:00:03
   ------------------------- -------------- 64.0/101.7 MB 13.4 MB/s eta 0:00:03
   ------------------------- -------------- 64.6/101.7 MB 13.4 MB/s eta 0:00:03
   ------------------------- -------------- 65.3/101.7 MB 13.4 MB/s eta 0:00:03
   ------------------------- -------------- 65.9/101.7 MB 13.4 MB/s eta 0:00:03
   -------------------------- ------------- 66.5/101.7 MB 13.4 MB/s eta 0:00:03
   -------------------------- ------------- 67.1/101.7 MB 13.6 MB/s eta 0:00:03
   -------------------------- ------------- 67.8/101.7 MB 13.4 MB/s eta 0:00:03
   -------------------------- ------------- 68.4/101.7 MB 13.4 MB/s eta 0:00:03
   --------------------------- ------------ 69.0/101.7 MB 13.6 MB/s eta 0:00:03
   --------------------------- ------------ 69.7/101.7 MB 13.6 MB/s eta 0:00:03
   --------------------------- ------------ 70.3/101.7 MB 13.6 MB/s eta 0:00:03
   --------------------------- ------------ 70.9/101.7 MB 13.6 MB/s eta 0:00:03
   ---------------------------- ----------- 71.6/101.7 MB 13.6 MB/s eta 0:00:03
   ---------------------------- ----------- 72.2/101.7 MB 13.6 MB/s eta 0:00:03
   ---------------------------- ----------- 72.8/101.7 MB 13.6 MB/s eta 0:00:03
   ---------------------------- ----------- 73.4/101.7 MB 13.6 MB/s eta 0:00:03
   ----------------------------- ---------- 74.1/101.7 MB 13.6 MB/s eta 0:00:03
   ----------------------------- ---------- 74.7/101.7 MB 13.6 MB/s eta 0:00:02
   ----------------------------- ---------- 75.4/101.7 MB 13.6 MB/s eta 0:00:02
   ----------------------------- ---------- 76.0/101.7 MB 13.6 MB/s eta 0:00:02
   ------------------------------ --------- 76.6/101.7 MB 13.6 MB/s eta 0:00:02
   ------------------------------ --------- 77.2/101.7 MB 13.4 MB/s eta 0:00:02
   ------------------------------ --------- 77.9/101.7 MB 13.4 MB/s eta 0:00:02
   ------------------------------ --------- 78.5/101.7 MB 13.6 MB/s eta 0:00:02
   ------------------------------- -------- 79.2/101.7 MB 13.6 MB/s eta 0:00:02
   ------------------------------- -------- 79.8/101.7 MB 13.4 MB/s eta 0:00:02
   ------------------------------- -------- 80.4/101.7 MB 13.4 MB/s eta 0:00:02
   ------------------------------- -------- 81.0/101.7 MB 13.6 MB/s eta 0:00:02
   -------------------------------- ------- 81.7/101.7 MB 13.6 MB/s eta 0:00:02
   -------------------------------- ------- 82.3/101.7 MB 13.6 MB/s eta 0:00:02
   -------------------------------- ------- 82.9/101.7 MB 13.4 MB/s eta 0:00:02
   -------------------------------- ------- 83.5/101.7 MB 13.6 MB/s eta 0:00:02
   --------------------------------- ------ 84.2/101.7 MB 13.6 MB/s eta 0:00:02
   --------------------------------- ------ 84.8/101.7 MB 13.6 MB/s eta 0:00:02
   --------------------------------- ------ 85.5/101.7 MB 13.6 MB/s eta 0:00:02
   --------------------------------- ------ 86.1/101.7 MB 13.6 MB/s eta 0:00:02
   ---------------------------------- ----- 86.7/101.7 MB 13.6 MB/s eta 0:00:02
   ---------------------------------- ----- 87.4/101.7 MB 13.6 MB/s eta 0:00:02
   ---------------------------------- ----- 88.0/101.7 MB 13.6 MB/s eta 0:00:02
   ---------------------------------- ----- 88.6/101.7 MB 13.6 MB/s eta 0:00:01
   ----------------------------------- ---- 89.3/101.7 MB 13.6 MB/s eta 0:00:01
   ----------------------------------- ---- 89.9/101.7 MB 13.6 MB/s eta 0:00:01
   ----------------------------------- ---- 90.5/101.7 MB 13.6 MB/s eta 0:00:01
   ----------------------------------- ---- 91.1/101.7 MB 13.6 MB/s eta 0:00:01
   ------------------------------------ --- 91.7/101.7 MB 13.6 MB/s eta 0:00:01
   ------------------------------------ --- 92.4/101.7 MB 13.6 MB/s eta 0:00:01
   ------------------------------------ --- 93.0/101.7 MB 13.6 MB/s eta 0:00:01
   ------------------------------------ --- 93.6/101.7 MB 13.6 MB/s eta 0:00:01
   ------------------------------------- -- 94.2/101.7 MB 13.6 MB/s eta 0:00:01
   ------------------------------------- -- 94.9/101.7 MB 13.6 MB/s eta 0:00:01
   ------------------------------------- -- 95.4/101.7 MB 13.4 MB/s eta 0:00:01
   ------------------------------------- -- 96.1/101.7 MB 13.6 MB/s eta 0:00:01
   -------------------------------------- - 96.8/101.7 MB 13.6 MB/s eta 0:00:01
   -------------------------------------- - 97.4/101.7 MB 13.6 MB/s eta 0:00:01
   -------------------------------------- - 98.0/101.7 MB 13.6 MB/s eta 0:00:01
   -------------------------------------- - 98.7/101.7 MB 13.6 MB/s eta 0:00:01
   -------------------------------------- - 99.0/101.7 MB 13.1 MB/s eta 0:00:01
   ---------------------------------------  99.7/101.7 MB 13.1 MB/s eta 0:00:01
   --------------------------------------  100.2/101.7 MB 13.1 MB/s eta 0:00:01
   --------------------------------------  100.8/101.7 MB 13.1 MB/s eta 0:00:01
   --------------------------------------  101.3/101.7 MB 12.8 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 12.9 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 12.9 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 12.9 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 12.9 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 12.9 MB/s eta 0:00:01
   --------------------------------------  101.7/101.7 MB 12.9 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 9.5 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

In [162]:
from xgboost import XGBClassifier

In [170]:
from lightgbm import LGBMClassifier

In [83]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\yashub hayat\anaconda3\lib\site-packages (3.9.4)
Requirement already satisfied: click in c:\users\yashub hayat\anaconda3\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\yashub hayat\anaconda3\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\yashub hayat\anaconda3\lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in c:\users\yashub hayat\anaconda3\lib\site-packages (from nltk) (4.66.4)
Requirement already satisfied: colorama in c:\users\yashub hayat\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [116]:
def clean_resume(text):

    text = str(text)

    # remove links
    text = re.sub(r'http\S+|www\S+|linkedin\S+|github\S+', ' ', text)

    # remove dates like Jan 2015, March 2012
    text = re.sub(
        r'\b(jan|january|feb|february|mar|march|apr|april|may|jun|june|jul|july|aug|august|sep|september|oct|october|nov|november|dec|december)\s+\d{4}\b',
        ' ',
        text,
        flags=re.IGNORECASE
    )

    # remove special characters
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # remove extra spaces/newlines
    text = re.sub(r'\s+', ' ', text)

    # lowercase
    text = text.lower().strip()

    return text

data["Resume_clean"] = data["Resume_str"].apply(clean_resume)

In [117]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def lemmatize_text(text):
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(w) for w in tokens if w not in stop_words]
    return ' '.join(tokens)

data["Resume_clean"] = data["Resume_clean"].apply(lemmatize_text)

In [119]:
le = LabelEncoder()
data["Category_encoded"] = le.fit_transform(data["Category"])

In [121]:
data.head()

         ID  \
0  16852973
1  22323967
2  33176873
3  27018550
4  17812897

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Resume_str  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           HR ADMINISTRATOR/MARKETING ASSOCIATE\n\nHR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate\n\nHR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate     Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         Assistant General Manager     Jun 2010   to   Dec 2010      Company Name   －   City  ,   State     Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  Handled daily operations and reported directly to the corporate office.  Hired and trained staff on overall objectives and goals with an emphasis on high customer service.  Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.         Executive Support / Marketing Assistant     Jul 2007   to   Jun 2010      Company Name   －   City  ,   State     Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.  Managed front-end operations to ensure friendly and efficient transactions.  Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         Reservation & Front Office Manager     Jun 2004   to   Jul 2007      Company Name   －   City  ,   State          Owner/ Partner     Dec 2001   to   May 2004      Company Name   －   City  ,   State          Price Integrity Coordinator     Aug 1999   to   Dec 2001      Company Name   －   City  ,   State          Education      N/A  ,   Business Administration   1999     Jefferson College   －   City  ,   State       Business Administration  Marketing / Advertising         High School Diploma  ,   College Prep. studies   1998     Sainte Genevieve Senior High   －   City  ,   State       Awarded American Shrubel Leadership Scholarship to Jefferson College         Skills     Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.

In [140]:
tfidf = TfidfVectorizer(max_features=10000, ngram_range=(1,2), sublinear_tf=True)

X = tfidf.fit_transform(data["Resume_clean"])
y = data["Category_encoded"]

In [141]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
lr_model = LogisticRegression(max_iter=1000, class_weight='balanced')
lr_model.fit(X_train, y_train)

y_pred = lr_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=le.classes_, zero_division=0))

Accuracy: 0.670020120724346
                        precision    recall  f1-score   support

            ACCOUNTANT       0.69      0.83      0.75        24
              ADVOCATE       0.48      0.46      0.47        24
           AGRICULTURE       0.70      0.54      0.61        13
               APPAREL       0.62      0.26      0.37        19
                  ARTS       0.55      0.29      0.38        21
            AUTOMOBILE       0.67      0.57      0.62         7
              AVIATION       0.86      0.75      0.80        24
               BANKING       0.94      0.70      0.80        23
                   BPO       1.00      0.25      0.40         4
  BUSINESS-DEVELOPMENT       0.56      0.83      0.67        24
                  CHEF       0.86      0.75      0.80        24
          CONSTRUCTION       0.81      0.77      0.79        22
            CONSULTANT       0.57      0.17      0.27        23
              DESIGNER       0.85      0.81      0.83        21
         DIGITAL-MEDIA       0.71      0.63      0.67        19
           ENGINEERING       0.75      0.75      0.75        24
               FINANCE       0.86      0.75      0.80        24
               FITNESS       0.76      0.70      0.73        23
            HEALTHCARE       0.54      0.61      0.57        23
                    HR       0.74      0.91      0.82        22
INFORMATION-TECHNOLOGY       0.71      1.00      0.83        24
      PUBLIC-RELATIONS       0.53      0.77      0.63        22
                 SALES       0.39      0.57      0.46        23
               TEACHER       0.55      0.85      0.67        20

              accuracy                           0.67       497
             macro avg       0.70      0.65      0.64       497
          weighted avg       0.69      0.67      0.66       497

In [127]:
print("Total resumes:", len(data))
print("\nCategory distribution:")
print(data["Category"].value_counts())

Total resumes: 2484

Category distribution:
Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
FINANCE                   118
ADVOCATE                  118
ACCOUNTANT                118
ENGINEERING               118
CHEF                      118
AVIATION                  117
FITNESS                   117
SALES                     116
BANKING                   115
HEALTHCARE                115
CONSULTANT                115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [134]:
print("Duplicate resumes:", data["Resume_clean"].duplicated().sum())

Duplicate resumes: 2

In [146]:
#second algorithm
svc_model = LinearSVC(class_weight='balanced', max_iter=2000)

#CalibratedClassifierCV wraps LinearSVC to fix the warning issue
svc_calibrated = CalibratedClassifierCV(svc_model)
svc_calibrated.fit(X_train, y_train)

y_pred_svc = svc_calibrated.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred_svc))
print(classification_report(y_test, y_pred_svc, target_names=le.classes_, zero_division=0))

Accuracy: 0.7323943661971831
                        precision    recall  f1-score   support

            ACCOUNTANT       0.80      0.83      0.82        24
              ADVOCATE       0.59      0.71      0.64        24
           AGRICULTURE       0.88      0.54      0.67        13
               APPAREL       0.64      0.37      0.47        19
                  ARTS       0.56      0.48      0.51        21
            AUTOMOBILE       1.00      0.29      0.44         7
              AVIATION       0.86      0.79      0.83        24
               BANKING       0.86      0.83      0.84        23
                   BPO       0.33      0.25      0.29         4
  BUSINESS-DEVELOPMENT       0.67      0.83      0.74        24
                  CHEF       0.85      0.71      0.77        24
          CONSTRUCTION       0.74      0.77      0.76        22
            CONSULTANT       0.67      0.52      0.59        23
              DESIGNER       0.90      0.90      0.90        21
         DIGITAL-MEDIA       0.73      0.58      0.65        19
           ENGINEERING       0.73      0.79      0.76        24
               FINANCE       0.91      0.83      0.87        24
               FITNESS       0.80      0.87      0.83        23
            HEALTHCARE       0.62      0.70      0.65        23
                    HR       0.88      0.95      0.91        22
INFORMATION-TECHNOLOGY       0.89      1.00      0.94        24
      PUBLIC-RELATIONS       0.63      0.77      0.69        22
                 SALES       0.47      0.61      0.53        23
               TEACHER       0.65      0.75      0.70        20

              accuracy                           0.73       497
             macro avg       0.74      0.69      0.70       497
          weighted avg       0.74      0.73      0.73       497

In [152]:
# algorithm3
nb_model = MultinomialNB(alpha=1.0)
nb_model.fit(X_train, y_train)

y_pred_nb = nb_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb, target_names=le.classes_, zero_division=0))

Accuracy: 0.5472837022132797
                        precision    recall  f1-score   support

            ACCOUNTANT       0.48      0.88      0.62        24
              ADVOCATE       0.28      0.38      0.32        24
           AGRICULTURE       1.00      0.08      0.14        13
               APPAREL       0.00      0.00      0.00        19
                  ARTS       0.67      0.10      0.17        21
            AUTOMOBILE       0.00      0.00      0.00         7
              AVIATION       0.83      0.62      0.71        24
               BANKING       0.82      0.61      0.70        23
                   BPO       0.00      0.00      0.00         4
  BUSINESS-DEVELOPMENT       0.41      0.88      0.56        24
                  CHEF       0.78      0.75      0.77        24
          CONSTRUCTION       0.65      0.68      0.67        22
            CONSULTANT       0.00      0.00      0.00        23
              DESIGNER       0.75      0.57      0.65        21
         DIGITAL-MEDIA       0.60      0.16      0.25        19
           ENGINEERING       0.68      0.62      0.65        24
               FINANCE       0.67      0.42      0.51        24
               FITNESS       0.68      0.65      0.67        23
            HEALTHCARE       0.52      0.57      0.54        23
                    HR       0.62      0.91      0.74        22
INFORMATION-TECHNOLOGY       0.53      1.00      0.70        24
      PUBLIC-RELATIONS       0.40      0.77      0.52        22
                 SALES       0.45      0.57      0.50        23
               TEACHER       0.47      0.70      0.56        20

              accuracy                           0.55       497
             macro avg       0.51      0.50      0.46       497
          weighted avg       0.54      0.55      0.50       497

In [156]:
rf_model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf, target_names=le.classes_, zero_division=0))

Accuracy: 0.7665995975855131
                        precision    recall  f1-score   support

            ACCOUNTANT       0.68      0.96      0.79        24
              ADVOCATE       1.00      0.79      0.88        24
           AGRICULTURE       1.00      0.62      0.76        13
               APPAREL       0.80      0.42      0.55        19
                  ARTS       0.50      0.14      0.22        21
            AUTOMOBILE       1.00      0.14      0.25         7
              AVIATION       0.78      0.88      0.82        24
               BANKING       0.83      0.65      0.73        23
                   BPO       1.00      0.25      0.40         4
  BUSINESS-DEVELOPMENT       0.88      0.88      0.88        24
                  CHEF       0.86      0.75      0.80        24
          CONSTRUCTION       0.86      0.86      0.86        22
            CONSULTANT       0.79      0.65      0.71        23
              DESIGNER       0.83      0.95      0.89        21
         DIGITAL-MEDIA       0.85      0.58      0.69        19
           ENGINEERING       0.78      0.88      0.82        24
               FINANCE       0.76      0.79      0.78        24
               FITNESS       0.79      0.83      0.81        23
            HEALTHCARE       0.64      0.70      0.67        23
                    HR       0.85      1.00      0.92        22
INFORMATION-TECHNOLOGY       0.73      1.00      0.84        24
      PUBLIC-RELATIONS       0.68      0.77      0.72        22
                 SALES       0.69      0.87      0.77        23
               TEACHER       0.56      1.00      0.71        20

              accuracy                           0.77       497
             macro avg       0.80      0.72      0.72       497
          weighted avg       0.78      0.77      0.75       497

In [164]:
xgb_model = XGBClassifier(n_estimators=200, random_state=42, eval_metric='mlogloss')
xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb, target_names=le.classes_, zero_division=0))

Accuracy: 0.7947686116700201
                        precision    recall  f1-score   support

            ACCOUNTANT       0.82      0.96      0.88        24
              ADVOCATE       0.83      0.83      0.83        24
           AGRICULTURE       1.00      0.46      0.63        13
               APPAREL       0.82      0.47      0.60        19
                  ARTS       0.57      0.62      0.59        21
            AUTOMOBILE       0.67      0.29      0.40         7
              AVIATION       0.95      0.83      0.89        24
               BANKING       0.82      0.78      0.80        23
                   BPO       1.00      0.25      0.40         4
  BUSINESS-DEVELOPMENT       0.81      0.92      0.86        24
                  CHEF       0.90      0.79      0.84        24
          CONSTRUCTION       0.90      0.86      0.88        22
            CONSULTANT       0.81      0.74      0.77        23
              DESIGNER       0.91      1.00      0.95        21
         DIGITAL-MEDIA       0.60      0.47      0.53        19
           ENGINEERING       0.76      0.92      0.83        24
               FINANCE       0.80      0.83      0.82        24
               FITNESS       0.79      0.83      0.81        23
            HEALTHCARE       0.78      0.78      0.78        23
                    HR       0.81      0.95      0.88        22
INFORMATION-TECHNOLOGY       0.78      0.88      0.82        24
      PUBLIC-RELATIONS       0.68      0.77      0.72        22
                 SALES       0.71      0.87      0.78        23
               TEACHER       0.78      0.90      0.84        20

              accuracy                           0.79       497
             macro avg       0.80      0.75      0.76       497
          weighted avg       0.80      0.79      0.79       497

In [172]:
lgbm_model = LGBMClassifier(
    n_estimators=200,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
lgbm_model.fit(X_train, y_train)

y_pred_lgbm = lgbm_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred_lgbm))
print(classification_report(y_test, y_pred_lgbm, target_names=le.classes_, zero_division=0))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.907281 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 217732
[LightGBM] [Info] Number of data points in the train set: 1987, number of used features: 6819
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Info] Start training from score -3.178054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

C:\Users\YASHUB HAYAT\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Accuracy: 0.8410462776659959
                        precision    recall  f1-score   support

            ACCOUNTANT       0.92      1.00      0.96        24
              ADVOCATE       0.88      0.88      0.88        24
           AGRICULTURE       1.00      0.62      0.76        13
               APPAREL       0.83      0.53      0.65        19
                  ARTS       0.72      0.62      0.67        21
            AUTOMOBILE       0.75      0.43      0.55         7
              AVIATION       0.91      0.83      0.87        24
               BANKING       0.83      0.83      0.83        23
                   BPO       0.00      0.00      0.00         4
  BUSINESS-DEVELOPMENT       0.92      1.00      0.96        24
                  CHEF       0.86      0.79      0.83        24
          CONSTRUCTION       0.90      0.86      0.88        22
            CONSULTANT       0.81      0.91      0.86        23
              DESIGNER       0.91      0.95      0.93        21
         DIGITAL-MEDIA       0.86      0.63      0.73        19
           ENGINEERING       0.79      0.92      0.85        24
               FINANCE       0.91      0.88      0.89        24
               FITNESS       0.77      0.87      0.82        23
            HEALTHCARE       0.87      0.87      0.87        23
                    HR       0.96      1.00      0.98        22
INFORMATION-TECHNOLOGY       0.92      1.00      0.96        24
      PUBLIC-RELATIONS       0.78      0.82      0.80        22
                 SALES       0.69      0.87      0.77        23
               TEACHER       0.75      0.90      0.82        20

              accuracy                           0.84       497
             macro avg       0.81      0.79      0.80       497
          weighted avg       0.84      0.84      0.84       497

In [174]:
import pickle

# Save LightGBM model
with open('resume_classifier.pkl', 'wb') as f:
    pickle.dump(lgbm_model, f)

# Save TF-IDF vectorizer
with open('tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(tfidf, f)

# Save Label Encoder
with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(le, f)

print("All files saved successfully!")

All files saved successfully!

In [176]:
# Load all saved files
with open('resume_classifier.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

with open('tfidf_vectorizer.pkl', 'rb') as f:
    loaded_tfidf = pickle.load(f)

with open('label_encoder.pkl', 'rb') as f:
    loaded_le = pickle.load(f)

print("All files loaded successfully!")

All files loaded successfully!

In [194]:
def predict_job_category(resume_text):
    cleaned = clean_resume(resume_text)
    lemmatized = lemmatize_text(cleaned)
    
    vectorized = loaded_tfidf.transform([lemmatized])
    vectorized_df = pd.DataFrame(
        vectorized.toarray(),
        columns=loaded_tfidf.get_feature_names_out()
    )
    
    prediction = loaded_model.predict(vectorized_df)
    category = loaded_le.inverse_transform(prediction)[0]
    return category

In [196]:
# Test on a sample resume from your dataset
sample_resume = data["Resume_clean"].iloc[0]
predicted_category = predict_job_category(sample_resume)
print("Predicted Category:", predicted_category)
print("Actual Category:", data["Category"].iloc[0])

Predicted Category: HR
Actual Category: HR

In [198]:
# Test on multiple resumes
for i in [0, 5, 10, 20, 50]:
    sample_resume = data["Resume_clean"].iloc[i]
    predicted = predict_job_category(sample_resume)
    actual = data["Category"].iloc[i]
    
    status = "✅" if predicted == actual else "❌"
    print(f"Resume_clean {i} → Predicted: {predicted} | Actual: {actual} {status}")

Resume_clean 0 → Predicted: HR | Actual: HR ✅
Resume_clean 5 → Predicted: HR | Actual: HR ✅
Resume_clean 10 → Predicted: HR | Actual: HR ✅
Resume_clean 20 → Predicted: HR | Actual: HR ✅
Resume_clean 50 → Predicted: HR | Actual: HR ✅

In [188]:
# Check what iloc 0, 5, 10, 20, 50 actually are
for i in [0, 5, 10, 20, 50]:
    print(f"Index {i} → Category: {data['Category'].iloc[i]}")

Index 0 → Category: HR
Index 5 → Category: HR
Index 10 → Category: HR
Index 20 → Category: HR
Index 50 → Category: HR

In [200]:
for i in [0, 50, 100, 200, 300, 400]:
    sample_resume = data["Resume_clean"].iloc[i]
    predicted = predict_job_category(sample_resume)
    actual = data["Category"].iloc[i]
    
    status = "✅" if predicted == actual else "❌"
    print(f"Resume_clean {i} → Predicted: {predicted} | Actual: {actual} {status}")

Resume_clean 0 → Predicted: HR | Actual: HR ✅
Resume_clean 50 → Predicted: HR | Actual: HR ✅
Resume_clean 100 → Predicted: HR | Actual: HR ✅
Resume_clean 200 → Predicted: DESIGNER | Actual: DESIGNER ✅
Resume_clean 300 → Predicted: INFORMATION-TECHNOLOGY | Actual: INFORMATION-TECHNOLOGY ✅
Resume_clean 400 → Predicted: TEACHER | Actual: TEACHER ✅

In [224]:
print(data["Category"].unique())

['HR' 'DESIGNER' 'INFORMATION-TECHNOLOGY' 'TEACHER' 'ADVOCATE'
 'BUSINESS-DEVELOPMENT' 'HEALTHCARE' 'FITNESS' 'AGRICULTURE' 'BPO' 'SALES'
 'CONSULTANT' 'DIGITAL-MEDIA' 'AUTOMOBILE' 'CHEF' 'FINANCE' 'APPAREL'
 'ENGINEERING' 'ACCOUNTANT' 'CONSTRUCTION' 'PUBLIC-RELATIONS' 'BANKING'
 'ARTS' 'AVIATION']